name = "Blooming"
author = "sammyette"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9af9c934d6a56783052b62c7121d371dd96a1f6fb859ba37ba7c1e8b5fcb131e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
