name = "Blooming"
author = "sammyette"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93c14a84b6e84b6c92f6cf1651d7c8e573ad60bdcd8c7ca71b65b15f028cce92"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
